# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 500220b7affab5922a8ff71a67efa19646a8471ee64ea43afc367592c7ae8f13de8f8572ebdf9bf228f58ba4b981eafd85f0081737d94584f410d69a3cb0cd6d

test:
  secret_key_base: ed737c7c15162b9e4cc12d7e8f269f9e9114178e7d2015fda45797f6a6b3560d123e0d8c93cfc92ce44b292b8ab6a4ed847b997983196c9e5e59550bbb86465b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
